C     version information: VERSN = char*64
      VERSN = '@(#) lib3.0 -  util:  January 1996'
      VERSN = '@(#) lib3.0 - WRIR draft, Kittle, Flynn, Hummel, Lumb'
      VERSN = '@(#) lib3.0 - EPA/600/3-89/034, Kittle, Hummel, Imhoff'
      VERSN = '@(#) lib3.0 - Contact: Kate Flynn, kmflynn@usgs.gov'
      VERSN = '@(#) lib3.0 - Version 2.0, 1994/05/27 (HASS tape 2)'
      VERSN = '@(#) lib3.0 - Version 2.1, update 1994/08/11'
      VERSN = '@(#) lib3.0 - Version 3.0, 1996/03/01 (HASS tape 3)'
