C
C     parameter to dimension special action conditionals
      INTEGER    MXSPCN,MXSPBK,MXSPCH,MXSPCR
      PARAMETER (MXSPCN=5000)
      PARAMETER (MXSPBK=5000)
      PARAMETER (MXSPCH=5000)
      PARAMETER (MXSPCR=15000)
C
C     MXSPCN - maximum number of comparison-conditions
C     MXSPCH - maximum number of conditional chains
C     MXSPBK - maximum number of logical blocks
C     MXSPCR - maximum number of chain references
C
